root = "."
tmp_dir = "tmp/air/provisioner"

[build]
cmd = "go build -o ./tmp/air/provisioner/manager ./cmd/main.go"
entrypoint = "./tmp/air/provisioner/manager provisioner"
full_bin = "./tmp/air/provisioner/manager provisioner"
include_ext = ["go"]
exclude_dir = ["bin", "dist", "site", "tmp", "vendor", ".git", ".venv", ".venv-docs"]
exclude_regex = ["_test\\.go"]
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

[log]
time = true

[screen]
clear_on_rebuild = true
