apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: lock-controller-statefulset-mutations
spec:
  policyName: lock-controller-statefulset-mutations
  validationActions:
    - Deny
