apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: openbao-enforce-managed-image-digests-binding
spec:
  policyName: openbao-enforce-managed-image-digests
  validationActions:
    - Deny
