apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: openbao-validate-openbaocluster-binding
spec:
  policyName: openbao-validate-openbaocluster
  validationActions:
    - Deny
