apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: openbao-validate-openbao-tenant-binding
spec:
  policyName: openbao-validate-openbao-tenant
  validationActions:
    - Deny
