apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: openbao-lock-managed-resource-mutations-binding
spec:
  policyName: openbao-lock-managed-resource-mutations
  validationActions:
    - Deny
