apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: openbao-lock-controller-statefulset-mutations-binding
spec:
  policyName: openbao-lock-controller-statefulset-mutations
  validationActions:
    - Deny
