apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"

configMapGenerator:
  - name: openbao-operator-grafana-dashboards
    files:
      - dashboards/overview.json
      - dashboards/backup-restore.json
      - dashboards/upgrades.json
      - dashboards/controller-runtime.json
