//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACMEConfig) DeepCopyInto(out *ACMEConfig) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACMEConfig.
func (in *ACMEConfig) DeepCopy() *ACMEConfig {
	if in == nil {
		return nil
	}
	out := new(ACMEConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSKMSSealConfig) DeepCopyInto(out *AWSKMSSealConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSKMSSealConfig.
func (in *AWSKMSSealConfig) DeepCopy() *AWSKMSSealConfig {
	if in == nil {
		return nil
	}
	out := new(AWSKMSSealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminOpsControllerStatus) DeepCopyInto(out *AdminOpsControllerStatus) {
	*out = *in
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(ControllerErrorStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminOpsControllerStatus.
func (in *AdminOpsControllerStatus) DeepCopy() *AdminOpsControllerStatus {
	if in == nil {
		return nil
	}
	out := new(AdminOpsControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditDevice) DeepCopyInto(out *AuditDevice) {
	*out = *in
	if in.FileOptions != nil {
		in, out := &in.FileOptions, &out.FileOptions
		*out = new(FileAuditOptions)
		**out = **in
	}
	if in.HTTPOptions != nil {
		in, out := &in.HTTPOptions, &out.HTTPOptions
		*out = new(HTTPAuditOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.SyslogOptions != nil {
		in, out := &in.SyslogOptions, &out.SyslogOptions
		*out = new(SyslogAuditOptions)
		**out = **in
	}
	if in.SocketOptions != nil {
		in, out := &in.SocketOptions, &out.SocketOptions
		*out = new(SocketAuditOptions)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditDevice.
func (in *AuditDevice) DeepCopy() *AuditDevice {
	if in == nil {
		return nil
	}
	out := new(AuditDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRollbackConfig) DeepCopyInto(out *AutoRollbackConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRollbackConfig.
func (in *AutoRollbackConfig) DeepCopy() *AutoRollbackConfig {
	if in == nil {
		return nil
	}
	out := new(AutoRollbackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureKeyVaultSealConfig) DeepCopyInto(out *AzureKeyVaultSealConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureKeyVaultSealConfig.
func (in *AzureKeyVaultSealConfig) DeepCopy() *AzureKeyVaultSealConfig {
	if in == nil {
		return nil
	}
	out := new(AzureKeyVaultSealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureTargetConfig) DeepCopyInto(out *AzureTargetConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureTargetConfig.
func (in *AzureTargetConfig) DeepCopy() *AzureTargetConfig {
	if in == nil {
		return nil
	}
	out := new(AzureTargetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendTLSConfig) DeepCopyInto(out *BackendTLSConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendTLSConfig.
func (in *BackendTLSConfig) DeepCopy() *BackendTLSConfig {
	if in == nil {
		return nil
	}
	out := new(BackendTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRetention) DeepCopyInto(out *BackupRetention) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRetention.
func (in *BackupRetention) DeepCopy() *BackupRetention {
	if in == nil {
		return nil
	}
	out := new(BackupRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSchedule) DeepCopyInto(out *BackupSchedule) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(BackupRetention)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSchedule.
func (in *BackupSchedule) DeepCopy() *BackupSchedule {
	if in == nil {
		return nil
	}
	out := new(BackupSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStatus) DeepCopyInto(out *BackupStatus) {
	*out = *in
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastAttemptScheduledTime != nil {
		in, out := &in.LastAttemptScheduledTime, &out.LastAttemptScheduledTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduledBackup != nil {
		in, out := &in.NextScheduledBackup, &out.NextScheduledBackup
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStatus.
func (in *BackupStatus) DeepCopy() *BackupStatus {
	if in == nil {
		return nil
	}
	out := new(BackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupTarget) DeepCopyInto(out *BackupTarget) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(GCSTargetConfig)
		**out = **in
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureTargetConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupTarget.
func (in *BackupTarget) DeepCopy() *BackupTarget {
	if in == nil {
		return nil
	}
	out := new(BackupTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenConfig) DeepCopyInto(out *BlueGreenConfig) {
	*out = *in
	if in.Verification != nil {
		in, out := &in.Verification, &out.Verification
		*out = new(VerificationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxJobFailures != nil {
		in, out := &in.MaxJobFailures, &out.MaxJobFailures
		*out = new(int32)
		**out = **in
	}
	if in.AutoRollback != nil {
		in, out := &in.AutoRollback, &out.AutoRollback
		*out = new(AutoRollbackConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenConfig.
func (in *BlueGreenConfig) DeepCopy() *BlueGreenConfig {
	if in == nil {
		return nil
	}
	out := new(BlueGreenConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenStatus) DeepCopyInto(out *BlueGreenStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.RollbackStartTime != nil {
		in, out := &in.RollbackStartTime, &out.RollbackStartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenStatus.
func (in *BlueGreenStatus) DeepCopy() *BlueGreenStatus {
	if in == nil {
		return nil
	}
	out := new(BlueGreenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakGlassStatus) DeepCopyInto(out *BreakGlassStatus) {
	*out = *in
	if in.EnteredAt != nil {
		in, out := &in.EnteredAt, &out.EnteredAt
		*out = (*in).DeepCopy()
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AcknowledgedAt != nil {
		in, out := &in.AcknowledgedAt, &out.AcknowledgedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakGlassStatus.
func (in *BreakGlassStatus) DeepCopy() *BreakGlassStatus {
	if in == nil {
		return nil
	}
	out := new(BreakGlassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerErrorStatus) DeepCopyInto(out *ControllerErrorStatus) {
	*out = *in
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerErrorStatus.
func (in *ControllerErrorStatus) DeepCopy() *ControllerErrorStatus {
	if in == nil {
		return nil
	}
	out := new(ControllerErrorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileAuditOptions) DeepCopyInto(out *FileAuditOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileAuditOptions.
func (in *FileAuditOptions) DeepCopy() *FileAuditOptions {
	if in == nil {
		return nil
	}
	out := new(FileAuditOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPCloudKMSSealConfig) DeepCopyInto(out *GCPCloudKMSSealConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPCloudKMSSealConfig.
func (in *GCPCloudKMSSealConfig) DeepCopy() *GCPCloudKMSSealConfig {
	if in == nil {
		return nil
	}
	out := new(GCPCloudKMSSealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSTargetConfig) DeepCopyInto(out *GCSTargetConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSTargetConfig.
func (in *GCSTargetConfig) DeepCopy() *GCSTargetConfig {
	if in == nil {
		return nil
	}
	out := new(GCSTargetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfig) DeepCopyInto(out *GatewayConfig) {
	*out = *in
	out.GatewayRef = in.GatewayRef
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.BackendTLS != nil {
		in, out := &in.BackendTLS, &out.BackendTLS
		*out = new(BackendTLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfig.
func (in *GatewayConfig) DeepCopy() *GatewayConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayReference) DeepCopyInto(out *GatewayReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayReference.
func (in *GatewayReference) DeepCopy() *GatewayReference {
	if in == nil {
		return nil
	}
	out := new(GatewayReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPAuditOptions) DeepCopyInto(out *HTTPAuditOptions) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAuditOptions.
func (in *HTTPAuditOptions) DeepCopy() *HTTPAuditOptions {
	if in == nil {
		return nil
	}
	out := new(HTTPAuditOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageVerificationConfig) DeepCopyInto(out *ImageVerificationConfig) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageVerificationConfig.
func (in *ImageVerificationConfig) DeepCopy() *ImageVerificationConfig {
	if in == nil {
		return nil
	}
	out := new(ImageVerificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressConfig) DeepCopyInto(out *IngressConfig) {
	*out = *in
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressConfig.
func (in *IngressConfig) DeepCopy() *IngressConfig {
	if in == nil {
		return nil
	}
	out := new(IngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitContainerConfig) DeepCopyInto(out *InitContainerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitContainerConfig.
func (in *InitContainerConfig) DeepCopy() *InitContainerConfig {
	if in == nil {
		return nil
	}
	out := new(InitContainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KMIPSealConfig) DeepCopyInto(out *KMIPSealConfig) {
	*out = *in
	if in.TLSSkipVerify != nil {
		in, out := &in.TLSSkipVerify, &out.TLSSkipVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KMIPSealConfig.
func (in *KMIPSealConfig) DeepCopy() *KMIPSealConfig {
	if in == nil {
		return nil
	}
	out := new(KMIPSealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerConfig) DeepCopyInto(out *ListenerConfig) {
	*out = *in
	if in.TLSDisable != nil {
		in, out := &in.TLSDisable, &out.TLSDisable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerConfig.
func (in *ListenerConfig) DeepCopy() *ListenerConfig {
	if in == nil {
		return nil
	}
	out := new(ListenerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
	if in.RotateBytes != nil {
		in, out := &in.RotateBytes, &out.RotateBytes
		*out = new(int64)
		**out = **in
	}
	if in.RotateMaxFiles != nil {
		in, out := &in.RotateMaxFiles, &out.RotateMaxFiles
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceConfig) DeepCopyInto(out *MaintenanceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceConfig.
func (in *MaintenanceConfig) DeepCopy() *MaintenanceConfig {
	if in == nil {
		return nil
	}
	out := new(MaintenanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfig) DeepCopyInto(out *NetworkConfig) {
	*out = *in
	if in.APIServerEndpointIPs != nil {
		in, out := &in.APIServerEndpointIPs, &out.APIServerEndpointIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EgressRules != nil {
		in, out := &in.EgressRules, &out.EgressRules
		*out = make([]networkingv1.NetworkPolicyEgressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IngressRules != nil {
		in, out := &in.IngressRules, &out.IngressRules
		*out = make([]networkingv1.NetworkPolicyIngressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfig.
func (in *NetworkConfig) DeepCopy() *NetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIKMSSealConfig) DeepCopyInto(out *OCIKMSSealConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIKMSSealConfig.
func (in *OCIKMSSealConfig) DeepCopy() *OCIKMSSealConfig {
	if in == nil {
		return nil
	}
	out := new(OCIKMSSealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoCluster) DeepCopyInto(out *OpenBaoCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoCluster.
func (in *OpenBaoCluster) DeepCopy() *OpenBaoCluster {
	if in == nil {
		return nil
	}
	out := new(OpenBaoCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoClusterList) DeepCopyInto(out *OpenBaoClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenBaoCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoClusterList.
func (in *OpenBaoClusterList) DeepCopy() *OpenBaoClusterList {
	if in == nil {
		return nil
	}
	out := new(OpenBaoClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoClusterSpec) DeepCopyInto(out *OpenBaoClusterSpec) {
	*out = *in
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = new(MaintenanceConfig)
		**out = **in
	}
	in.TLS.DeepCopyInto(&out.TLS)
	in.Storage.DeepCopyInto(&out.Storage)
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(OpenBaoConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupSchedule)
		(*in).DeepCopyInto(*out)
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(RestoreConfig)
		**out = **in
	}
	if in.SelfInit != nil {
		in, out := &in.SelfInit, &out.SelfInit
		*out = new(SelfInitConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InitContainer != nil {
		in, out := &in.InitContainer, &out.InitContainer
		*out = new(InitContainerConfig)
		**out = **in
	}
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = make([]AuditDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]Plugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(UpgradeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Unseal != nil {
		in, out := &in.Unseal, &out.Unseal
		*out = new(UnsealConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageVerification != nil {
		in, out := &in.ImageVerification, &out.ImageVerification
		*out = new(ImageVerificationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OperatorImageVerification != nil {
		in, out := &in.OperatorImageVerification, &out.OperatorImageVerification
		*out = new(ImageVerificationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadHardening != nil {
		in, out := &in.WorkloadHardening, &out.WorkloadHardening
		*out = new(WorkloadHardeningConfig)
		**out = **in
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.UpdateStrategy.DeepCopyInto(&out.UpdateStrategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoClusterSpec.
func (in *OpenBaoClusterSpec) DeepCopy() *OpenBaoClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OpenBaoClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoClusterStatus) DeepCopyInto(out *OpenBaoClusterStatus) {
	*out = *in
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(UpgradeProgress)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.BlueGreen != nil {
		in, out := &in.BlueGreen, &out.BlueGreen
		*out = new(BlueGreenStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.OperationLock != nil {
		in, out := &in.OperationLock, &out.OperationLock
		*out = new(OperationLockStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.BreakGlass != nil {
		in, out := &in.BreakGlass, &out.BreakGlass
		*out = new(BreakGlassStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadControllerStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.AdminOps != nil {
		in, out := &in.AdminOps, &out.AdminOps
		*out = new(AdminOpsControllerStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoClusterStatus.
func (in *OpenBaoClusterStatus) DeepCopy() *OpenBaoClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OpenBaoClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoConfiguration) DeepCopyInto(out *OpenBaoConfiguration) {
	*out = *in
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(bool)
		**out = **in
	}
	if in.Listener != nil {
		in, out := &in.Listener, &out.Listener
		*out = new(ListenerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Raft != nil {
		in, out := &in.Raft, &out.Raft
		*out = new(RaftConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Plugin != nil {
		in, out := &in.Plugin, &out.Plugin
		*out = new(PluginConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CacheSize != nil {
		in, out := &in.CacheSize, &out.CacheSize
		*out = new(int64)
		**out = **in
	}
	if in.DisableCache != nil {
		in, out := &in.DisableCache, &out.DisableCache
		*out = new(bool)
		**out = **in
	}
	if in.DetectDeadlocks != nil {
		in, out := &in.DetectDeadlocks, &out.DetectDeadlocks
		*out = new(bool)
		**out = **in
	}
	if in.RawStorageEndpoint != nil {
		in, out := &in.RawStorageEndpoint, &out.RawStorageEndpoint
		*out = new(bool)
		**out = **in
	}
	if in.IntrospectionEndpoint != nil {
		in, out := &in.IntrospectionEndpoint, &out.IntrospectionEndpoint
		*out = new(bool)
		**out = **in
	}
	if in.ImpreciseLeaseRoleTracking != nil {
		in, out := &in.ImpreciseLeaseRoleTracking, &out.ImpreciseLeaseRoleTracking
		*out = new(bool)
		**out = **in
	}
	if in.UnsafeAllowAPIAuditCreation != nil {
		in, out := &in.UnsafeAllowAPIAuditCreation, &out.UnsafeAllowAPIAuditCreation
		*out = new(bool)
		**out = **in
	}
	if in.AllowAuditLogPrefixing != nil {
		in, out := &in.AllowAuditLogPrefixing, &out.AllowAuditLogPrefixing
		*out = new(bool)
		**out = **in
	}
	if in.EnableResponseHeaderHostname != nil {
		in, out := &in.EnableResponseHeaderHostname, &out.EnableResponseHeaderHostname
		*out = new(bool)
		**out = **in
	}
	if in.EnableResponseHeaderRaftNodeID != nil {
		in, out := &in.EnableResponseHeaderRaftNodeID, &out.EnableResponseHeaderRaftNodeID
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoConfiguration.
func (in *OpenBaoConfiguration) DeepCopy() *OpenBaoConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenBaoConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoRestore) DeepCopyInto(out *OpenBaoRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoRestore.
func (in *OpenBaoRestore) DeepCopy() *OpenBaoRestore {
	if in == nil {
		return nil
	}
	out := new(OpenBaoRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoRestoreList) DeepCopyInto(out *OpenBaoRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenBaoRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoRestoreList.
func (in *OpenBaoRestoreList) DeepCopy() *OpenBaoRestoreList {
	if in == nil {
		return nil
	}
	out := new(OpenBaoRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoRestoreSpec) DeepCopyInto(out *OpenBaoRestoreSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoRestoreSpec.
func (in *OpenBaoRestoreSpec) DeepCopy() *OpenBaoRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(OpenBaoRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoRestoreStatus) DeepCopyInto(out *OpenBaoRestoreStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoRestoreStatus.
func (in *OpenBaoRestoreStatus) DeepCopy() *OpenBaoRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(OpenBaoRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoTenant) DeepCopyInto(out *OpenBaoTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoTenant.
func (in *OpenBaoTenant) DeepCopy() *OpenBaoTenant {
	if in == nil {
		return nil
	}
	out := new(OpenBaoTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoTenantList) DeepCopyInto(out *OpenBaoTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenBaoTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoTenantList.
func (in *OpenBaoTenantList) DeepCopy() *OpenBaoTenantList {
	if in == nil {
		return nil
	}
	out := new(OpenBaoTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenBaoTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoTenantSpec) DeepCopyInto(out *OpenBaoTenantSpec) {
	*out = *in
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(v1.ResourceQuotaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LimitRange != nil {
		in, out := &in.LimitRange, &out.LimitRange
		*out = new(v1.LimitRangeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoTenantSpec.
func (in *OpenBaoTenantSpec) DeepCopy() *OpenBaoTenantSpec {
	if in == nil {
		return nil
	}
	out := new(OpenBaoTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenBaoTenantStatus) DeepCopyInto(out *OpenBaoTenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenBaoTenantStatus.
func (in *OpenBaoTenantStatus) DeepCopy() *OpenBaoTenantStatus {
	if in == nil {
		return nil
	}
	out := new(OpenBaoTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationLockStatus) DeepCopyInto(out *OperationLockStatus) {
	*out = *in
	if in.AcquiredAt != nil {
		in, out := &in.AcquiredAt, &out.AcquiredAt
		*out = (*in).DeepCopy()
	}
	if in.RenewedAt != nil {
		in, out := &in.RenewedAt, &out.RenewedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationLockStatus.
func (in *OperationLockStatus) DeepCopy() *OperationLockStatus {
	if in == nil {
		return nil
	}
	out := new(OperationLockStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKCS11SealConfig) DeepCopyInto(out *PKCS11SealConfig) {
	*out = *in
	if in.GenerateKey != nil {
		in, out := &in.GenerateKey, &out.GenerateKey
		*out = new(bool)
		**out = **in
	}
	if in.RSAEncryptLocal != nil {
		in, out := &in.RSAEncryptLocal, &out.RSAEncryptLocal
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKCS11SealConfig.
func (in *PKCS11SealConfig) DeepCopy() *PKCS11SealConfig {
	if in == nil {
		return nil
	}
	out := new(PKCS11SealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Plugin) DeepCopyInto(out *Plugin) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Plugin.
func (in *Plugin) DeepCopy() *Plugin {
	if in == nil {
		return nil
	}
	out := new(Plugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginConfig) DeepCopyInto(out *PluginConfig) {
	*out = *in
	if in.FileUID != nil {
		in, out := &in.FileUID, &out.FileUID
		*out = new(int64)
		**out = **in
	}
	if in.AutoDownload != nil {
		in, out := &in.AutoDownload, &out.AutoDownload
		*out = new(bool)
		**out = **in
	}
	if in.AutoRegister != nil {
		in, out := &in.AutoRegister, &out.AutoRegister
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfig.
func (in *PluginConfig) DeepCopy() *PluginConfig {
	if in == nil {
		return nil
	}
	out := new(PluginConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RaftAutopilotConfig) DeepCopyInto(out *RaftAutopilotConfig) {
	*out = *in
	if in.CleanupDeadServers != nil {
		in, out := &in.CleanupDeadServers, &out.CleanupDeadServers
		*out = new(bool)
		**out = **in
	}
	if in.MinQuorum != nil {
		in, out := &in.MinQuorum, &out.MinQuorum
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RaftAutopilotConfig.
func (in *RaftAutopilotConfig) DeepCopy() *RaftAutopilotConfig {
	if in == nil {
		return nil
	}
	out := new(RaftAutopilotConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RaftConfig) DeepCopyInto(out *RaftConfig) {
	*out = *in
	if in.PerformanceMultiplier != nil {
		in, out := &in.PerformanceMultiplier, &out.PerformanceMultiplier
		*out = new(int32)
		**out = **in
	}
	if in.Autopilot != nil {
		in, out := &in.Autopilot, &out.Autopilot
		*out = new(RaftAutopilotConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RaftConfig.
func (in *RaftConfig) DeepCopy() *RaftConfig {
	if in == nil {
		return nil
	}
	out := new(RaftConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreConfig) DeepCopyInto(out *RestoreConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreConfig.
func (in *RestoreConfig) DeepCopy() *RestoreConfig {
	if in == nil {
		return nil
	}
	out := new(RestoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSource) DeepCopyInto(out *RestoreSource) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSource.
func (in *RestoreSource) DeepCopy() *RestoreSource {
	if in == nil {
		return nil
	}
	out := new(RestoreSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfInitAuditDevice) DeepCopyInto(out *SelfInitAuditDevice) {
	*out = *in
	if in.FileOptions != nil {
		in, out := &in.FileOptions, &out.FileOptions
		*out = new(FileAuditOptions)
		**out = **in
	}
	if in.HTTPOptions != nil {
		in, out := &in.HTTPOptions, &out.HTTPOptions
		*out = new(HTTPAuditOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.SyslogOptions != nil {
		in, out := &in.SyslogOptions, &out.SyslogOptions
		*out = new(SyslogAuditOptions)
		**out = **in
	}
	if in.SocketOptions != nil {
		in, out := &in.SocketOptions, &out.SocketOptions
		*out = new(SocketAuditOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfInitAuditDevice.
func (in *SelfInitAuditDevice) DeepCopy() *SelfInitAuditDevice {
	if in == nil {
		return nil
	}
	out := new(SelfInitAuditDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfInitAuthMethod) DeepCopyInto(out *SelfInitAuthMethod) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfInitAuthMethod.
func (in *SelfInitAuthMethod) DeepCopy() *SelfInitAuthMethod {
	if in == nil {
		return nil
	}
	out := new(SelfInitAuthMethod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfInitConfig) DeepCopyInto(out *SelfInitConfig) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make([]SelfInitRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfInitConfig.
func (in *SelfInitConfig) DeepCopy() *SelfInitConfig {
	if in == nil {
		return nil
	}
	out := new(SelfInitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfInitPolicy) DeepCopyInto(out *SelfInitPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfInitPolicy.
func (in *SelfInitPolicy) DeepCopy() *SelfInitPolicy {
	if in == nil {
		return nil
	}
	out := new(SelfInitPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfInitRequest) DeepCopyInto(out *SelfInitRequest) {
	*out = *in
	if in.AuditDevice != nil {
		in, out := &in.AuditDevice, &out.AuditDevice
		*out = new(SelfInitAuditDevice)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthMethod != nil {
		in, out := &in.AuthMethod, &out.AuthMethod
		*out = new(SelfInitAuthMethod)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretEngine != nil {
		in, out := &in.SecretEngine, &out.SecretEngine
		*out = new(SelfInitSecretEngine)
		(*in).DeepCopyInto(*out)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(SelfInitPolicy)
		**out = **in
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfInitRequest.
func (in *SelfInitRequest) DeepCopy() *SelfInitRequest {
	if in == nil {
		return nil
	}
	out := new(SelfInitRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfInitSecretEngine) DeepCopyInto(out *SelfInitSecretEngine) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfInitSecretEngine.
func (in *SelfInitSecretEngine) DeepCopy() *SelfInitSecretEngine {
	if in == nil {
		return nil
	}
	out := new(SelfInitSecretEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfig) DeepCopyInto(out *ServiceConfig) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfig.
func (in *ServiceConfig) DeepCopy() *ServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SocketAuditOptions) DeepCopyInto(out *SocketAuditOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SocketAuditOptions.
func (in *SocketAuditOptions) DeepCopy() *SocketAuditOptions {
	if in == nil {
		return nil
	}
	out := new(SocketAuditOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticSealConfig) DeepCopyInto(out *StaticSealConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticSealConfig.
func (in *StaticSealConfig) DeepCopy() *StaticSealConfig {
	if in == nil {
		return nil
	}
	out := new(StaticSealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyslogAuditOptions) DeepCopyInto(out *SyslogAuditOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyslogAuditOptions.
func (in *SyslogAuditOptions) DeepCopy() *SyslogAuditOptions {
	if in == nil {
		return nil
	}
	out := new(SyslogAuditOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.ACME != nil {
		in, out := &in.ACME, &out.ACME
		*out = new(ACMEConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraSANs != nil {
		in, out := &in.ExtraSANs, &out.ExtraSANs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryConfig) DeepCopyInto(out *TelemetryConfig) {
	*out = *in
	if in.MaximumGaugeCardinality != nil {
		in, out := &in.MaximumGaugeCardinality, &out.MaximumGaugeCardinality
		*out = new(int32)
		**out = **in
	}
	if in.DogStatsdTags != nil {
		in, out := &in.DogStatsdTags, &out.DogStatsdTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryConfig.
func (in *TelemetryConfig) DeepCopy() *TelemetryConfig {
	if in == nil {
		return nil
	}
	out := new(TelemetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitSealConfig) DeepCopyInto(out *TransitSealConfig) {
	*out = *in
	if in.DisableRenewal != nil {
		in, out := &in.DisableRenewal, &out.DisableRenewal
		*out = new(bool)
		**out = **in
	}
	if in.TLSSkipVerify != nil {
		in, out := &in.TLSSkipVerify, &out.TLSSkipVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitSealConfig.
func (in *TransitSealConfig) DeepCopy() *TransitSealConfig {
	if in == nil {
		return nil
	}
	out := new(TransitSealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnsealConfig) DeepCopyInto(out *UnsealConfig) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticSealConfig)
		**out = **in
	}
	if in.Transit != nil {
		in, out := &in.Transit, &out.Transit
		*out = new(TransitSealConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AWSKMS != nil {
		in, out := &in.AWSKMS, &out.AWSKMS
		*out = new(AWSKMSSealConfig)
		**out = **in
	}
	if in.AzureKeyVault != nil {
		in, out := &in.AzureKeyVault, &out.AzureKeyVault
		*out = new(AzureKeyVaultSealConfig)
		**out = **in
	}
	if in.GCPCloudKMS != nil {
		in, out := &in.GCPCloudKMS, &out.GCPCloudKMS
		*out = new(GCPCloudKMSSealConfig)
		**out = **in
	}
	if in.KMIP != nil {
		in, out := &in.KMIP, &out.KMIP
		*out = new(KMIPSealConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OCIKMS != nil {
		in, out := &in.OCIKMS, &out.OCIKMS
		*out = new(OCIKMSSealConfig)
		**out = **in
	}
	if in.PKCS11 != nil {
		in, out := &in.PKCS11, &out.PKCS11
		*out = new(PKCS11SealConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnsealConfig.
func (in *UnsealConfig) DeepCopy() *UnsealConfig {
	if in == nil {
		return nil
	}
	out := new(UnsealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStrategy) DeepCopyInto(out *UpdateStrategy) {
	*out = *in
	if in.BlueGreen != nil {
		in, out := &in.BlueGreen, &out.BlueGreen
		*out = new(BlueGreenConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStrategy.
func (in *UpdateStrategy) DeepCopy() *UpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(UpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeConfig) DeepCopyInto(out *UpgradeConfig) {
	*out = *in
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeConfig.
func (in *UpgradeConfig) DeepCopy() *UpgradeConfig {
	if in == nil {
		return nil
	}
	out := new(UpgradeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeProgress) DeepCopyInto(out *UpgradeProgress) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedPods != nil {
		in, out := &in.CompletedPods, &out.CompletedPods
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.LastStepDownTime != nil {
		in, out := &in.LastStepDownTime, &out.LastStepDownTime
		*out = (*in).DeepCopy()
	}
	if in.LastErrorAt != nil {
		in, out := &in.LastErrorAt, &out.LastErrorAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeProgress.
func (in *UpgradeProgress) DeepCopy() *UpgradeProgress {
	if in == nil {
		return nil
	}
	out := new(UpgradeProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationHookConfig) DeepCopyInto(out *ValidationHookConfig) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationHookConfig.
func (in *ValidationHookConfig) DeepCopy() *ValidationHookConfig {
	if in == nil {
		return nil
	}
	out := new(ValidationHookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationConfig) DeepCopyInto(out *VerificationConfig) {
	*out = *in
	if in.PrePromotionHook != nil {
		in, out := &in.PrePromotionHook, &out.PrePromotionHook
		*out = new(ValidationHookConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationConfig.
func (in *VerificationConfig) DeepCopy() *VerificationConfig {
	if in == nil {
		return nil
	}
	out := new(VerificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadControllerStatus) DeepCopyInto(out *WorkloadControllerStatus) {
	*out = *in
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(ControllerErrorStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadControllerStatus.
func (in *WorkloadControllerStatus) DeepCopy() *WorkloadControllerStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadHardeningConfig) DeepCopyInto(out *WorkloadHardeningConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadHardeningConfig.
func (in *WorkloadHardeningConfig) DeepCopy() *WorkloadHardeningConfig {
	if in == nil {
		return nil
	}
	out := new(WorkloadHardeningConfig)
	in.DeepCopyInto(out)
	return out
}
