{{- include "approval.validate" . -}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "approval.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
  {{- include "approval.prerequisiteAnnotations" . | nindent 2 }}
automountServiceAccountToken: false
---
{{- end }}
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-approval
  namespace: {{ .Values.cluster.namespace }}
  {{- include "approval.prerequisiteAnnotations" . | nindent 2 }}
spec:
  podSelector:
    matchLabels:
      openbao.org/cluster: {{ .Values.cluster.name }}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: openbao-policy-approval
              openbao.org/approval-target: {{ include "approval.target" . | quote }}
      ports:
        - protocol: TCP
          port: 8200
{{- end }}
