FROM gcr.io/distroless/static:nonroot@sha256:f512d819b8f109f2375e8b51d8cfd8aafe81034bc3e319740128b7d7f70d5036

ARG BIN_DIR=bin/linux_amd64

COPY ${BIN_DIR}/bao-upgrade-executor /upgrade-executor

# User 1000:1000
USER 1000:1000
WORKDIR /

HEALTHCHECK NONE
ENTRYPOINT ["/upgrade-executor"]
