package openbaocluster

import "time"

// Reason constants for OpenBaoCluster conditions.
const (
	ReasonGatewayAPIMissing                    = "GatewayAPIMissing"
	ReasonOIDCBootstrapConfigurationInvalid    = "OIDCBootstrapConfigurationInvalid"
	ReasonAPIServerNetworkConfigurationInvalid = "APIServerNetworkConfigurationInvalid"
	ReasonPrerequisitesMissing                 = "PrerequisitesMissing"
	ReasonPrerequisitesReady                   = "PrerequisitesReady"
	ReasonAdmissionPoliciesNotReady            = "AdmissionPoliciesNotReady"
	ReasonAdmissionPoliciesReady               = "AdmissionPoliciesReady"

	ReasonInProgress = "InProgress"

	ReasonLeaderFound                            = "LeaderFound"
	ReasonLeaderUnknown                          = "LeaderUnknown"
	ReasonMultipleLeaders                        = "MultipleLeaders"
	ReasonInitialized                            = "Initialized"
	ReasonNotInitialized                         = "NotInitialized"
	ReasonSealed                                 = "Sealed"
	ReasonUnsealed                               = "Unsealed"
	ReasonAppArmorUnsupported                    = "AppArmorUnsupported"
	ReasonEtcdEncryptionUnknown                  = "EtcdEncryptionUnknown"
	ReasonDevelopmentProfile                     = "DevelopmentProfile"
	ReasonAmbientUnsealIdentity                  = "AmbientUnsealIdentity"
	ReasonProfileNotSet                          = "ProfileNotSet"
	ReasonProductionReady                        = "ProductionReady"
	ReasonProductionNotReady                     = "ProductionNotReady"
	ReasonTransitAddressNotHTTPS                 = "TransitAddressNotHTTPS"
	ReasonTransitInlineToken                     = "TransitInlineToken"
	ReasonUnsealTLSSkipVerify                    = "UnsealTLSSkipVerify"
	ReasonUserAccessConfigured                   = "UserAccessConfigured"
	ReasonUserAccessUnverified                   = "UserAccessUnverified"
	ReasonRootTokenStored                        = "RootTokenStored"
	ReasonStaticUnsealInUse                      = "StaticUnsealInUse"
	ReasonOperatorManagedTLS                     = "OperatorManagedTLS"
	ReasonSecurityViolation                      = "SecurityViolation"
	ReasonTLSSecretMissing                       = "TLSSecretMissing"
	ReasonTLSSecretInvalid                       = "TLSSecretInvalid"
	ReasonACMEIntegrationReady                   = "ACMEIntegrationReady"
	ReasonACMECacheReady                         = "ACMECacheReady"
	ReasonGatewayIntegrationReady                = "GatewayIntegrationReady"
	ReasonAPIServerNetworkReady                  = "APIServerNetworkReady"
	ReasonAPIServerEndpointIPsRecommended        = "APIServerEndpointIPsRecommended"
	ReasonGatewayReferenceMissing                = "GatewayReferenceMissing"
	ReasonGatewayClassMissing                    = "GatewayClassMissing"
	ReasonGatewayClassPending                    = "GatewayClassPending"
	ReasonGatewayClassNotAccepted                = "GatewayClassNotAccepted"
	ReasonGatewayVersionUnsupported              = "GatewayVersionUnsupported"
	ReasonGatewayFeatureUnsupported              = "GatewayFeatureUnsupported"
	ReasonGatewayCapabilitiesUnknown             = "GatewayCapabilitiesUnknown"
	ReasonGatewayNotProgrammed                   = "GatewayNotProgrammed"
	ReasonGatewayProgrammingPending              = "GatewayProgrammingPending"
	ReasonGatewayListenerIncompatible            = "GatewayListenerIncompatible"
	ReasonACMECacheNotConfigured                 = "ACMECacheNotConfigured"
	ReasonACMECacheMissing                       = "ACMECacheMissing"
	ReasonACMECachePending                       = "ACMECachePending"
	ReasonACMECacheInvalidAccessMode             = "ACMECacheInvalidAccessMode"
	ReasonACMEDomainNotResolvable                = "ACMEDomainNotResolvable"
	ReasonACMEGatewayNotConfiguredForPassthrough = "ACMEGatewayNotConfiguredForPassthrough"
	ReasonDisabled                               = "Disabled"
	ReasonNotReady                               = "NotReady"
	ReasonAllReplicasReady                       = "AllReplicasReady"
	ReasonNoReplicasReady                        = "NoReplicasReady"

	ReasonStorageInvalidSize             = "StorageInvalidSize"
	ReasonStorageShrinkNotSupported      = "StorageShrinkNotSupported"
	ReasonStorageResizeNotSupported      = "StorageResizeNotSupported"
	ReasonStorageClassChangeNotSupported = "StorageClassChangeNotSupported"
	ReasonStorageRestartRequired         = "StorageRestartRequired"
	ReasonInvalidVersion                 = "InvalidVersion"
	ReasonDowngradeBlocked               = "DowngradeBlocked"
	ReasonImageVersionMismatch           = "ImageVersionMismatch"
	ReasonStorageClassConfigured         = "StorageClassConfigured"
	ReasonStorageClassPending            = "StorageClassPending"
	ReasonStorageClassDefaulted          = "StorageClassDefaulted"
	ReasonStorageClassUnset              = "StorageClassUnset"
	ReasonStorageClassMismatch           = "StorageClassMismatch"
	ReasonStorageClassInconsistent       = "StorageClassInconsistent"

	reasonReady              = "Ready"
	reasonPaused             = "Paused"
	reasonReconciling        = "Reconciling"
	reasonIdle               = "Idle"
	reasonUnknown            = "Unknown"
	reasonBreakGlassRequired = "BreakGlassRequired"

	controllerNameWorkload = "openbaocluster-workload"
	controllerNameAdminOps = "openbaocluster-adminops"
	controllerNameStatus   = "openbaocluster-status"

	annotationLastDevelopmentWarning   = "openbao.org/last-development-warning"
	annotationLastAmbientUnsealNote    = "openbao.org/last-ambient-unseal-identity-note"
	annotationLastProfileNotSetWarning = "openbao.org/last-profile-not-set-warning"
	annotationLastRootTokenWarning     = "openbao.org/last-root-token-warning"
	annotationLastStaticUnsealWarning  = "openbao.org/last-static-unseal-warning"
)

const securityWarningInterval = time.Hour
